# This file is part of Hedgehog.
#
# Copyright 2023 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: new-release
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      release:
        type: string
        description: Release name in the form of `release-x.y`
        required: true
jobs:
  new-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create the branch if it doesn't exists
        # Get the tags in reverse version (-V) sort order
        run: |
          git checkout -b ${{ inputs.release }} || git switch ${{ inputs.release }}
          git push --set-upstream origin ${{ inputs.release }}
